name: Android Manual Build

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (debug/release)'     
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
      upload-artifact:
        description: 'Upload APK as artifact'
        required: true
        default: 'true'
        type: boolean

env:
  ANDROID_MIN_SDK_VERSION: 30
  ANDROID_TARGET_SDK_VERSION: 33
  ANDROID_BUILD_TOOLS_VERSION: "30.0.3"
  ANDROID_NDK_VERSION: "25.2.9519653"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Configure Gradle Wrapper
      run: |
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip" > gradle/wrapper/gradle-wrapper.properties
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}
        platform-version: ${{ env.ANDROID_TARGET_SDK_VERSION }}
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
    
    - name: Install required SDK packages
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ env.ANDROID_TARGET_SDK_VERSION }}"
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ env.ANDROID_MIN_SDK_VERSION }}"
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        ./gradlew assemble${{ inputs.build-type }} \
          -PminSdkVersion=${{ env.ANDROID_MIN_SDK_VERSION }} \
          -PtargetSdkVersion=${{ env.ANDROID_TARGET_SDK_VERSION }} \
          -PcompileSdkVersion=${{ env.ANDROID_TARGET_SDK_VERSION }}
    
    - name: Upload APK
      if: ${{ inputs.upload-artifact }}
      uses: actions/upload-artifact@v3
      with:
        name: sumi-emulator-${{ inputs.build-type }}
        path: app/build/outputs/apk/${{ inputs.build-type }}/app-${{ inputs.build-type }}.apk
