name: Build Android APK Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git history in versioning

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            src/android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('src/android/**/gradle-wrapper.properties', 'src/android/**/*.gradle*', 'src/android/**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --validate-url --gradle-version 8.1.1
        working-directory: ./src/android
        shell: cmd

      - name: Build with Gradle
        run: ./gradlew --no-daemon --stacktrace --warning-mode=all --scan assembleMainlineRelease
        working-directory: ./src/android
        shell: cmd
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-mainline-release-apk
          path: src/android/app/build/outputs/apk/mainline/release/*.apk
          if-no-files-found: error
