name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANDROID_MIN_SDK_VERSION: 30
  ANDROID_TARGET_SDK_VERSION: 33
  ANDROID_BUILD_TOOLS_VERSION: "30.0.3"
  ANDROID_NDK_VERSION: "25.2.9519653" # Updated NDK while keeping Gradle 7.x

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Configure Gradle Wrapper
      run: |
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip" > gradle/wrapper/gradle-wrapper.properties
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}
        platform-version: ${{ env.ANDROID_TARGET_SDK_VERSION }}
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
        cmake-version: "3.22.1"
    
    - name: Install specific SDK packages
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ env.ANDROID_TARGET_SDK_VERSION }}"
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-${{ env.ANDROID_MIN_SDK_VERSION }}"
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug \
          -PminSdkVersion=${{ env.ANDROID_MIN_SDK_VERSION }} \
          -PtargetSdkVersion=${{ env.ANDROID_TARGET_SDK_VERSION }} \
          -PcompileSdkVersion=${{ env.ANDROID_TARGET_SDK_VERSION }}
    
    - name: Upload APK
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: sumi-emulator-apk
        path: app/build/outputs/apk/debug/app-debug.apk
